In [1]:
height = 1.797
wight =68.1

In [10]:
print(height)
print(wight)

1.797
68.1


In [11]:
# BMI CALCUATION Wight/height**2
BMI = wight/height ** 2
print(BMI)

21.088755791278917


In [1]:
#python list 

value = [12, 23, 45, 50]
print(value)

[12, 23, 45, 50]


In [ ]:
value_names = ["raghu", 124425, "rajesh", 45775, "ajay", 48785, "dattu", 57878]
print(value_names)

['raghu', 124425, 'rajesh', 45775, 'ajay', 48785, 'dattu', 57878]


In [100]:
#list slicing
value_names[2:6]

['rajesh', 45775, 'ajay', 48785]

In [101]:
value_names[:2]

['raghu', 124425]

In [102]:
# adding element in list
value_names + ["shiva", 45788]


['raghu',
 124425,
 'rajesh',
 45775,
 'ajay',
 48785,
 'dattu',
 57878,
 'shiva',
 45788]

In [103]:
#deleting element form list
del(value_names[-1])
print(value_names)

['raghu', 124425, 'rajesh', 45775, 'ajay', 48785, 'dattu']


In [104]:
# list inside a list
value_list = [["raghu", 25454],["rahul", 587878]]
print(value_list)
type(value_list)

[['raghu', 25454], ['rahul', 587878]]


list

In [105]:
value_list[-1]

['rahul', 587878]

In [106]:
max(value_list)

['rahul', 587878]

In [107]:
# import of numpy for array

import numpy as np

In [108]:
height1 = [1.754, 1.458, 1.245, 1.545, 1.245]

In [109]:
wight1 = [70, 59, 60, 72, 74]

In [110]:
pheight = np.array(height1)
pwight = np.array(wight1)
type(pheight)
type(pwight)

numpy.ndarray

In [111]:
bmi1 = pwight/pheight**2
print(bmi1)
type(bmi1)

[22.75301022 27.75472724 38.70905308 30.16306909 47.74116547]


numpy.ndarray

In [122]:
#condition check on bmi

bmi1[bmi1 > 40]

array([47.74116547])

In [125]:
#python list

list2 = [1, 2, 3, 4, 5]

#array list
arraylist = np.array([1, 2, 3, 4, 5])

print(list2 + list2)

con = arraylist + arraylist
print(con)

con[con > 7]

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]


array([ 8, 10])

In [126]:
# 2D array NumPy array

np_2d = np.array([[1.75, 1.45, 1.59, 1.78, 1.66], [58, 53, 72, 66, 65]])
print(np_2d)

[[ 1.75  1.45  1.59  1.78  1.66]
 [58.   53.   72.   66.   65.  ]]


In [131]:
np_2d[1][0]

58.0

In [135]:
np_2d[np_2d > 1]

array([ 1.75,  1.45,  1.59,  1.78,  1.66, 58.  , 53.  , 72.  , 66.  ,
       65.  ])

In [145]:
print(sum(np_2d[0]))
print(max(np_2d[0]))


8.23
1.78
